In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive/')
# Load the data, and separate the target
%cd /content/drive/My Drive/cshw1/
dx = pd.read_csv('x_train.csv')
print(dx)
dy = pd.read_csv('y_train.csv')
print(dy)
dxtest = pd.read_csv('x_test.csv')
print(dxtest)
dytest = pd.read_csv('y_test.csv')
print(dytest)

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/My Drive/cshw1
      the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
0       2   5    2    0    2   0   24    1    0   4  ...             0   
1      18  15    2    1    4  14  120    5    0  15  ...             0   
2       2   0    1    1    2   2   12    2    0   3  ...             0   
3      26  31    2   13   12  23  222    1    0  65  ...             0   
4       1   1    1    2    0   0   10    0    0   1  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
4132    2  10    6    1    1   0   46    0    4   5  ...             0   
4133    5   8    6    1    3   3  128    1    1  26  ...             0   
4134    2   0    1    1    0   0    7    0    0   1  ...             0   
4135    3   6    2    3    1   4   54    7    0  10  ...             0   
4136    0   0    1    0  

In [ ]:
features = list(dx.columns)
print(features)

['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in', 'on', 'is', 'this', 'enron', 'i', 'be', 'that', 'will', 'have', 'with', 'your', 'at', 'we', 's', 'are', 'it', 'by', 'com', 'as', 'from', 'gas', 'or', 'not', 'me', 'deal', 'if', 'meter', 'hpl', 'please', 're', 'e', 'any', 'our', 'corp', 'can', 'd', 'all', 'has', 'was', 'know', 'need', 'an', 'forwarded', 'new', 't', 'may', 'up', 'j', 'mmbtu', 'should', 'do', 'am', 'get', 'out', 'see', 'no', 'there', 'price', 'daren', 'but', 'been', 'company', 'l', 'these', 'let', 'so', 'would', 'm', 'into', 'xls', 'farmer', 'attached', 'us', 'information', 'they', 'message', 'day', 'time', 'my', 'one', 'what', 'only', 'http', 'th', 'volume', 'mail', 'contract', 'which', 'month', 'more', 'robert', 'sitara', 'about', 'texas', 'nom', 'energy', 'pec', 'questions', 'www', 'deals', 'volumes', 'pm', 'ena', 'now', 'their', 'file', 'some', 'email', 'just', 'also', 'call', 'change', 'other', 'here', 'like', 'b', 'flow', 'net', 'following', 'p', 'pro

In [ ]:
print(dx.shape)
print(dx.head())
print(dy.head())
print(dy.shape)


(4137, 3000)
   the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  connevey  \
0    2   5    2    0    2   0   24    1    0   4  ...             0         0   
1   18  15    2    1    4  14  120    5    0  15  ...             0         0   
2    2   0    1    1    2   2   12    2    0   3  ...             0         0   
3   26  31    2   13   12  23  222    1    0  65  ...             0         0   
4    1   1    1    2    0   0   10    0    0   1  ...             0         0   

   jay  valued  lay  infrastructure  military  allowing  ff  dry  
0    0       0    0               0         0         0   0    0  
1    0       0    0               0         0         0   2    0  
2    0       0    0               0         0         0   1    0  
3    0       0    5               0         0         0   0    0  
4    0       0    0               0         0         0   0    0  

[5 rows x 3000 columns]
   Prediction
0           0
1           0
2           1
3           1
4  

In [ ]:
count0 = (dy == 0).sum()[0]
count1 = (dy == 1).sum()[0]
print('Count of zeros: ', count0,'\n')
print('Count of ones: ',count1)
percentage_spam = count1/(count0+count1)
print('Percentage of spam mails is:',percentage_spam)
percentage_not_spam = count0/(count0+count1)
print(percentage_not_spam)

Count of zeros:  2954 

Count of ones:  1183
Percentage of spam mails is: 0.2859560067681895
0.7140439932318104


In [ ]:
data = pd.concat([dx, dy], axis=1)
data.head()

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  valued  \
0    2   5    2    0    2   0   24    1    0   4  ...         0    0       0   
1   18  15    2    1    4  14  120    5    0  15  ...         0    0       0   
2    2   0    1    1    2   2   12    2    0   3  ...         0    0       0   
3   26  31    2   13   12  23  222    1    0  65  ...         0    0       0   
4    1   1    1    2    0   0   10    0    0   1  ...         0    0       0   

   lay  infrastructure  military  allowing  ff  dry  Prediction  
0    0               0         0         0   0    0           0  
1    0               0         0         0   2    0           0  
2    0               0         0         0   1    0           1  
3    5               0         0         0   0    0           1  
4    0               0         0         0   0    0           1  

[5 rows x 3001 columns]

In [ ]:
row_sums = data.iloc[:, :-1].sum(axis=1)
print(row_sums)
sum_of_cols = data.iloc[:, :-1].sum()
print(sum_of_cols)

0        560
1       2254
2        375
3       4696
4        152
        ... 
4132    1177
4133    2359
4134     163
4135    1132
4136      79
Length: 4137, dtype: int64
the               27476
to                25758
ect               21445
and               12817
for               12944
                  ...  
infrastructure       17
military             19
allowing             15
ff                 3852
dry                  28
Length: 3000, dtype: int64


In [ ]:
sum_of_cols_for_respondent_0 = data.groupby('Prediction').get_group(0).drop(columns='Prediction').sum()
print('Sum of columns for which the respondent is 0:\n',sum_of_cols_for_respondent_0.head())

sum_of_cols_for_respondent_1 = data.groupby('Prediction').get_group(1).drop(columns='Prediction').sum()
print('Sum of columns for which the respondent is 1:\n',sum_of_cols_for_respondent_1.head())

Sum of columns for which the respondent is 0:
 the    19765
to     17335
ect    18442
and     7927
for     9307
dtype: int64
Sum of columns for which the respondent is 1:
 the    7711
to     8423
ect    3003
and    4890
for    3637
dtype: int64


In [ ]:
sum_of_rows_where_respondent_is_0 = data.groupby('Prediction').get_group(0).drop(columns='Prediction').sum(axis=1)
print(sum_of_rows_where_respondent_is_0)

total_sum_of_rows_where_respondent_is_0 = sum_of_rows_where_respondent_is_0.sum()
print('All words for non-spam mails:',total_sum_of_rows_where_respondent_is_0)

sum_of_rows_where_respondent_is_1 = data.groupby('Prediction').get_group(1).drop(columns='Prediction').sum(axis=1)
print(sum_of_rows_where_respondent_is_1)

total_sum_of_rows_where_respondent_is_1 = sum_of_rows_where_respondent_is_1.sum()
print('All words for spam mails:',total_sum_of_rows_where_respondent_is_1)

0        560
1       2254
5        286
6        103
7        673
        ... 
4126      86
4127    2985
4132    1177
4134     163
4136      79
Length: 2954, dtype: int64
All words for non-spam mails: 3100894
2        375
3       4696
4        152
12      2697
13      1053
        ... 
4129    8437
4130     779
4131     334
4133    2359
4135    1132
Length: 1183, dtype: int64
All words for spam mails: 1746526


In [ ]:
result_series_0 = (sum_of_cols_for_respondent_0 / total_sum_of_rows_where_respondent_is_0).replace(0,10**(-12)).apply(np.log)
print(result_series_0,'\n')
result_series_1 = (sum_of_cols_for_respondent_1 / total_sum_of_rows_where_respondent_is_1).replace(0,10**(-12)).apply(np.log)
print(result_series_1)

the               -5.055533
to                -5.186718
ect               -5.124815
and               -5.969171
for               -5.808679
                    ...    
infrastructure   -13.155442
military         -14.254054
allowing         -12.644616
ff                -7.352317
dry              -11.951469
Length: 3000, dtype: float64 

the               -5.422736
to                -5.334418
ect               -6.365772
and               -5.878192
for               -6.174225
                    ...    
infrastructure   -11.975244
military         -11.539926
allowing         -12.763701
ff                -6.842659
dry              -12.293698
Length: 3000, dtype: float64


In [ ]:
def multinomial_predictor(result_series_0,result_series_1,dxtest):
  new_series_0 = dxtest.multiply(result_series_0, axis=1).sum(axis=1)
  new_series_0_w_prior = new_series_0 + np.log(0.71)
  new_series_1 = dxtest.multiply(result_series_1, axis=1).sum(axis=1)
  new_series_1_w_prior = new_series_1 + np.log(0.29)
  compared_series_boolean = new_series_1_w_prior.gt(new_series_0_w_prior)
  compared_series = compared_series_boolean.astype(int)
  return compared_series

In [ ]:
trained_y = multinomial_predictor(result_series_0,result_series_1,dxtest)
print(trained_y)

0       0
1       0
2       0
3       1
4       0
       ..
1030    1
1031    0
1032    1
1033    0
1034    1
Length: 1035, dtype: int64


In [ ]:
trained_y_df = trained_y.to_frame()
print(trained_y_df)

      0
0     0
1     0
2     0
3     1
4     0
...  ..
1030  1
1031  0
1032  1
1033  0
1034  1

[1035 rows x 1 columns]


In [ ]:
trained_y_df.shape

(1035, 1)

In [ ]:
dytest.shape

(1035, 1)

In [ ]:
trained_y_df.eq(dytest.values).mean()

0    0.958454
dtype: float64

In [ ]:
dytest.rename(columns = {'Prediction':'actual y'}, inplace = True)
print(dytest)

      actual y
0            0
1            0
2            0
3            1
4            0
...        ...
1030         1
1031         0
1032         1
1033         0
1034         1

[1035 rows x 1 columns]


In [ ]:
trained_y_df.rename(columns = {0:'trained y'}, inplace = True)
print(trained_y_df)

      trained y
0             0
1             0
2             0
3             1
4             0
...         ...
1030          1
1031          0
1032          1
1033          0
1034          1

[1035 rows x 1 columns]


In [ ]:
df_concat = pd.concat([dytest,trained_y_df], axis=1)
confusion_matrix = pd.crosstab(df_concat['actual y'], df_concat['trained y'], rownames=['Actual'], colnames=['Predicted'])
print(confusion_matrix)

Predicted    0    1
Actual             
0          693   25
1           18  299


In [ ]:
sum_of_cols_for_respondent_0_2 = sum_of_cols_for_respondent_0 + 5
print(sum_of_cols_for_respondent_0_2)
sum_of_cols_for_respondent_1_2 = sum_of_cols_for_respondent_1 + 5
print(sum_of_cols_for_respondent_1_2)

the               19770
to                17340
ect               18447
and                7932
for                9312
                  ...  
infrastructure       11
military              7
allowing             15
ff                 1993
dry                  25
Length: 3000, dtype: int64
the               7716
to                8428
ect               3008
and               4895
for               3642
                  ... 
infrastructure      16
military            22
allowing            10
ff                1869
dry                 13
Length: 3000, dtype: int64


In [ ]:
total_sum_of_rows_where_respondent_is_0_2 = total_sum_of_rows_where_respondent_is_0 + 15000
print(total_sum_of_rows_where_respondent_is_0_2)
total_sum_of_rows_where_respondent_is_1_2 = total_sum_of_rows_where_respondent_is_1 +15000
print(total_sum_of_rows_where_respondent_is_1_2)

3115894
1761526


In [ ]:
result_series_0_2 = (sum_of_cols_for_respondent_0_2/ total_sum_of_rows_where_respondent_is_0_2).replace(0,10**(-12)).apply(np.log)
print(result_series_0_2,'\n')
result_series_1_2 = (sum_of_cols_for_respondent_1_2/ total_sum_of_rows_where_respondent_is_1_2).replace(0,10**(-12)).apply(np.log)
print(result_series_1_2)

the               -5.060106
to                -5.191255
ect               -5.129370
and               -5.973366
for               -5.812967
                    ...    
infrastructure   -12.554131
military         -13.006117
allowing         -12.243976
ff                -7.354630
dry              -11.733151
Length: 3000, dtype: float64 

the               -5.430640
to                -5.342376
ect               -6.372660
and               -5.885721
for               -6.181403
                    ...    
infrastructure   -11.609102
military         -11.290649
allowing         -12.079106
ff                -6.848532
dry              -11.816742
Length: 3000, dtype: float64


In [ ]:
trained_y_2 = multinomial_predictor(result_series_0_2,result_series_1_2,dxtest)
print(trained_y_2)

0       0
1       0
2       0
3       1
4       0
       ..
1030    1
1031    0
1032    1
1033    0
1034    1
Length: 1035, dtype: int64


In [ ]:
trained_y_2_df = trained_y_2.to_frame()
print(trained_y_2_df)

      0
0     0
1     0
2     0
3     1
4     0
...  ..
1030  1
1031  0
1032  1
1033  0
1034  1

[1035 rows x 1 columns]


In [ ]:
trained_y_2_df.eq(dytest.values).mean()

0    0.947826
dtype: float64

In [ ]:
trained_y_2_df.rename(columns = {0:'trained y'}, inplace = True)
print(trained_y_2_df)

      trained y
0             0
1             0
2             0
3             1
4             0
...         ...
1030          1
1031          0
1032          1
1033          0
1034          1

[1035 rows x 1 columns]


In [ ]:
df_concat_2 = pd.concat([dytest,trained_y_2_df], axis=1)
confusion_matrix = pd.crosstab(df_concat_2['actual y'], df_concat_2['trained y'], rownames=['Actual'], colnames=['Predicted'])
print(confusion_matrix)

Predicted    0    1
Actual             
0          681   37
1           17  300


In [ ]:
label = data.iloc[:, -1]

In [ ]:
counts_label_0 = np.count_nonzero(data.loc[label.values == 0, :], axis=0)
counts_label_0 = counts_label_0[:-1]
print(counts_label_0)

[2244 2316 2954 ...   10  878   16]


In [ ]:
counts_label_1 = np.count_nonzero(data.loc[label.values == 1, :], axis=0)
counts_label_1 = counts_label_1[:-1]
print(counts_label_1)

[ 845  977 1183 ...    5  603    8]


In [ ]:
pred0 = counts_label_0/count0
print(pred0)
pred1 = counts_label_1/count1
print(pred1)

[0.75964794 0.78402167 1.         ... 0.00338524 0.2972241  0.00541638]
[0.71428571 0.82586644 1.         ... 0.00422654 0.50972105 0.00676247]


In [ ]:
pred0_reverse = 1 - pred0
print(pred0_reverse)
pred1_reverse = 1 - pred1
print(pred1_reverse)

[0.24035206 0.21597833 0.         ... 0.99661476 0.7027759  0.99458362]
[0.28571429 0.17413356 0.         ... 0.99577346 0.49027895 0.99323753]


In [ ]:
boolean_dxtest = dxtest.astype(bool).astype(int)
print(boolean_dxtest)

      the  to  ect  and  for  of  a  you  hou  in  ...  enhancements  \
0       1   1    1    0    1   0  1    0    0   1  ...             0   
1       0   0    1    0    1   0  1    0    0   0  ...             0   
2       1   1    1    1    1   1  1    1    1   1  ...             0   
3       0   1    1    1    1   1  1    0    1   1  ...             0   
4       1   1    1    1    1   1  1    0    0   1  ...             0   
...   ...  ..  ...  ...  ...  .. ..  ...  ...  ..  ...           ...   
1030    1   1    1    1    1   1  1    1    1   1  ...             0   
1031    1   1    1    1    1   1  1    1    0   1  ...             0   
1032    1   1    1    1    1   1  1    1    1   1  ...             0   
1033    1   1    1    0    1   0  1    0    0   1  ...             0   
1034    0   0    1    0    1   0  1    1    0   0  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
0            0    0       0    0               0       

In [ ]:
boolean_reverse = 1 - boolean_dxtest
print(boolean_reverse)

      the  to  ect  and  for  of  a  you  hou  in  ...  enhancements  \
0       0   0    0    1    0   1  0    1    1   0  ...             1   
1       1   1    0    1    0   1  0    1    1   1  ...             1   
2       0   0    0    0    0   0  0    0    0   0  ...             1   
3       1   0    0    0    0   0  0    1    0   0  ...             1   
4       0   0    0    0    0   0  0    1    1   0  ...             1   
...   ...  ..  ...  ...  ...  .. ..  ...  ...  ..  ...           ...   
1030    0   0    0    0    0   0  0    0    0   0  ...             1   
1031    0   0    0    0    0   0  0    0    1   0  ...             1   
1032    0   0    0    0    0   0  0    0    0   0  ...             1   
1033    0   0    0    1    0   1  0    1    1   0  ...             1   
1034    1   1    0    1    0   1  0    0    1   1  ...             1   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
0            1    1       1    1               1       

In [ ]:
result0_firsthalf = boolean_dxtest.mul(pred0, axis=1)
#print(result0_firsthalf)
result0_secondhalf = boolean_reverse.mul(pred0_reverse, axis = 1)
#print(result0_secondhalf)
sumof_results = (result0_firsthalf+result0_secondhalf).replace(0,10*(-12))
#print(sumof_results)
multiof_results = sumof_results.prod(axis=1)
logof_results = multiof_results.apply(np.log)
print(multiof_results)
print(logof_results)

0        3.501219e-89
1        8.953025e-84
2       7.062115e-187
3      -2.694751e-133
4       3.374756e-204
            ...      
1030    1.015723e-171
1031     8.623953e-87
1032    6.465168e-179
1033    7.524413e-101
1034     7.950495e-82
Length: 1035, dtype: float64
0      -203.676962
1      -191.225156
2      -428.628668
3              NaN
4      -468.511036
           ...    
1030   -393.726450
1031   -198.170360
1032   -410.296303
1033   -230.542942
1034   -186.738743
Length: 1035, dtype: float64


In [ ]:
row_products_0 = result0_firsthalf.prod(axis=1)
print(row_products_0.apply(np.log))

0      -inf
1      -inf
2      -inf
3      -inf
4      -inf
       ... 
1030   -inf
1031   -inf
1032   -inf
1033   -inf
1034   -inf
Length: 1035, dtype: float64


In [ ]:
def bernoulli_predictor(boolean_dxtest,pred0,pred1):
  pred0_reverse = 1 - pred0
  pred1_reverse = 1 - pred1
  boolean_reverse = 1 - boolean_dxtest

  result0_firsthalf = boolean_dxtest.mul(pred0, axis=1)
  result0_secondhalf = boolean_reverse.mul(pred0_reverse, axis = 1)
  prediction0 = (result0_firsthalf+result0_secondhalf).replace(0,10**(-12)).prod(axis=1).apply(np.log)
  new_pred0 = prediction0 + np.log(0.71)

  result1_firsthalf = boolean_dxtest.mul(pred1, axis=1)
  result1_secondhalf = boolean_reverse.mul(pred1_reverse, axis = 1)
  prediction1 = (result1_firsthalf+result1_secondhalf).replace(0,10**(-12)).prod(axis=1).apply(np.log)
  new_pred1 = prediction1 + np.log(0.29)

  compared_series = new_pred1.gt(new_pred0).astype(int)
  return compared_series

In [ ]:
trained_b = bernoulli_predictor(boolean_dxtest,pred0,pred1)

In [ ]:
trained_b_df = trained_b.to_frame()

In [ ]:
trained_b_df.eq(dytest.values).mean()

0    0.887923
dtype: float64

In [ ]:
dytest.rename(columns = {'Prediction':'actual y'}, inplace = True)
print(dytest)

      actual y
0            0
1            0
2            0
3            1
4            0
...        ...
1030         1
1031         0
1032         1
1033         0
1034         1

[1035 rows x 1 columns]


In [ ]:
trained_b_df.rename(columns = {0:'trained y'}, inplace = True)
print(trained_y_df)

      trained y
0             0
1             0
2             0
3             1
4             0
...         ...
1030          1
1031          0
1032          1
1033          0
1034          1

[1035 rows x 1 columns]


In [ ]:
df_concat_b = pd.concat([dytest,trained_y_df], axis=1)
confusion_matrix = pd.crosstab(df_concat_b['actual y'], df_concat_b['trained y'], rownames=['Actual'], colnames=['Predicted'])
print(confusion_matrix)

Predicted    0    1
Actual             
0          693   25
1           18  299
